[#notes-on-using-aide]
= Notes on using AIDE
:doctype: revision-notes
:author: Peter Lawrey
:lang: en-GB
:toc:


It is helpful to keep notes on how the project is progressing and what changes you have made. This can help you to understand the project better and to make the necessary changes at the end to make it complete.

NOTE: This document can be a template for recording notes on your own project and to help the AI suggest improvements as it is also a source of information between phases.

== First Phase
Create a skeleton for the project and see what the AI can generate for you. These are more a source of inspiration than a source of truth.

- Suggest areas for improvement
- Generate missing requirements, code, and/or tests
- Make many changes

== Second Phase
Bring the project in sync

- Update the requirements from the code and tests
- Update the tests from the requirements and code
- Update the code from the requirements and tests

== Third Phase
Review the project

- Look at more specific improvements
- Make selective changes

== Fourth Phase
Restructure the project to make it easier to work with

- Refactor the requirements, code, and/or tests to make them easier for the AI to work with and understand.

== Fifth Phase
Finalize the project

- Review the changes made in the previous phases to ensure they are consistent and correct.
- Make any necessary corrections or adjustments yourself once you feel you aren't advancing further.

NOTE: You have to have an understanding of the project to make the necessary changes at the end to make it complete. If you don't understand something, ask for clarification or skip it and possibly come back to it later.
